### ISSUE TITLE
Help trying to write a custom recipe

### ISSUE THREAD

**Issue by adrianherrera** [Samsung/kflat#2]
Hi team!

First, thanks for the really cool tool.

I am trying to write a recipe to dump the device tree of a kernel module; specifically, the `struct device_node` defined [here](https://github.com/torvalds/linux/blob/master/include/linux/of.h#L48-L68). I am interested in `properties` and `child`ren of a device node.

Here is what I have so far:

```c
FUNCTION_DECLARE_FLATTEN_STRUCT(property);
FUNCTION_DECLARE_FLATTEN_STRUCT(device_node);

FUNCTION_DEFINE_FLATTEN_STRUCT(property,
    AGGREGATE_FLATTEN_STRING(name);
    //AGGREGATE_FLATTEN_TYPE(int, length); <-- This does not compile :(
    // TODO: How to include `void *value`?
    AGGREGATE_FLATTEN_STRUCT(property, next);
);
FUNCTION_DEFINE_FLATTEN_STRUCT(device_node,
    AGGREGATE_FLATTEN_STRING(name);
    AGGREGATE_FLATTEN_STRING(full_name);
    AGGREGATE_FLATTEN_STRUCT(property, properties);
    AGGREGATE_FLATTEN_STRUCT(device_node, child);
    // TODO: How to include `void *data`?
    // TODO: How to include `unsigned int unique_id`?
);
```

My questions are:

1. How to declare the `int` and `void*` elements I want to flatten? I thought I could use `AGGREGATE_FLATTEN_TYPE`, but this returns an error.
2. Is declaring `AGGREGATE_FLATTEN_STRUCT(property, next);` enough to capture the linked list representation of the `properties`/`next` elements? Or do I need to use something like `AGGREGATE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED_SHIFTED`, which is what the other examples use?

**Comment by bzator** [comment]
Hello Adrian,

Thank you for your interest in KFLAT. Let me clarify some points regarding recipe preparation.

When you're writing recipes for a given struct type you only need to take care of pointer members (unless the pointer is hidden inside some other built-in type as the `__rb_parent_color` member in the `struct rb_root` type in the kernel).

When you write the following:
```c
FUNCTION_DEFINE_FLATTEN_STRUCT(property, ...)
```
it defines a function that will first copy the memory region occupied by the instance of this `struct property` and later on it will execute the interal recipes (`AGGREGATE_*`) that you've specified in your recipe. That means the value of the `length` member will be copied during the first stage and will be preserved in the output image.

Different situation is when you have a pointer member inside your struct type. In that case it usually points to some other memory area that you want to copy as well. Moreover the pointer value most likely will not have any sensible meaning in the output image whenever loaded into different address space. The interal recipes (`AGGREGATE_*`) handle both of these problems. It will run the recipes for the pointee member types and translate the pointer values into indexes from the beginning of the output image.

So the solution to the first problem:
```c
//AGGREGATE_FLATTEN_TYPE(int, length); <-- This does not compile :(
```
is just to remove this recipe.

Now handling `void*` pointers is rather tricky.

When you have this member:
```c
struct property *next;
```
you can tell that it points to another instance of the `struct property` but when you have `void*` it can point to practically anything. In such case you have to analyze the source code for your specific use case and provide a recipe for the type that this member actually points to.

So let's assume that in your case (i.e. in the context of some function that triggers flattening some kernel data) this `void*` actually points to say buffer of 10 integer values. You could then write the recipe as follows:
```c
AGGREGATE_FLATTEN_TYPE_ARRAY(int, value, 10);
```

If the number of integer values is given by the member `length` you can write the following recipe:
```c
AGGREGATE_FLATTEN_TYPE_ARRAY(int, value, ATTR(length));
```

If it happens that the void* actually points to a C-string then you write proper recipe for that:
```c
AGGREGATE_FLATTEN_STRING(value);
```
etc. We don't have a recipe for a generic `void*` pointer as we have to know the exact layout of the pointed memory to properly serialize it.

Unfortunately preparation of precise recipes for the Linux kernel structures is a very difficult problem. If you're interested I discussed this topic during Open Source Summit last year:
https://youtu.be/Ynunpuk-Vfo?si=EQb4VQ8XvE3U0z1q&t=1291

The current status quo is that you can generate recipes that works for most cases but you'll need to handle edge cases (like `void*` pointers that resolves ambiguously) by fixing them by hand.

Regarding the `next` member of `struct property` it looks like in this case it's a simple singly linked list and each `next` member points exactly to another instance of this structure. In such case it's enough to use `AGGREGATE_FLATTEN_STRUCT(property, next);` as you mentioned. It will iteratively follow all pointers until the final `next` has the value 0.

The examples that use `AGGREGATE_FLATTEN_STRUCT_ARRAY_SELF_CONTAINED_SHIFTED` are usually more complicated. These handle cases where the list is defined through so called anchor objects like `struct list_head`. For example:

```c
struct my_struct {
	/* (...) */
	struct list_head my_list;
	/* (...) */
}
```

Now `my_list.next` points to `my_list` in the another instance of `struct my_struct` but in order to properly serialize the `struct my_struct` object in its entirety we have to pass an offset from the `my_list` member to the beginning of this structure. This is what the `*_SHIFTED` family of recipes is used for (we provide additional shift value to the pointer).

Finally the `SELF_CONTAINED` family of recipes is used whenever you cannot include the type definition of the structure in your recipe code (for example this type is defined privately in some other C file). Normally it's enough to use `AGGREGATE_FLATTEN_STRUCT_ARRAY_SHIFTED` macro in which case  you can refer to the members by name.

I hope it will help you. If you have any more questions regarding preparation of recipes feel free to ask them here.

Best Regards,
Bartosz Zator

**Comment by adrianherrera** [comment]
Hi @bzator,

Perfect! Thanks soooo much for your explanations, that's super helpful.

I've fixed up my recipe so it now looks like the following:

```c
FUNCTION_DECLARE_FLATTEN_STRUCT(property);
FUNCTION_DECLARE_FLATTEN_STRUCT(device_node);

FUNCTION_DEFINE_FLATTEN_STRUCT(property, AGGREGATE_FLATTEN_STRING(name);
 //                              AGGREGATE_FLATTEN_TYPE_ARRAY(u8, value,
 //                                                           ATTR(length));
                               AGGREGATE_FLATTEN_STRUCT(property, next););
FUNCTION_DEFINE_FLATTEN_STRUCT(device_node, AGGREGATE_FLATTEN_STRING(name);
                               AGGREGATE_FLATTEN_STRING(full_name);
                               AGGREGATE_FLATTEN_STRUCT(property, properties);
                               AGGREGATE_FLATTEN_STRUCT(property, deadprops);
                               AGGREGATE_FLATTEN_STRUCT(device_node, parent);
                               AGGREGATE_FLATTEN_STRUCT(device_node, child);
                               AGGREGATE_FLATTEN_STRUCT(device_node, sibling););
```

Turns out, that `void *data` field in the `struct device_node` wasn't particularly interesting, so I removed it.

It works great, **except** for when I use `AGGREGATE_FLATTEN_TYPE_ARRAY(u8, value, ATTR(length))`. When I remove this, it works fine. When I include it, I get the following log in my `dmesg`:

```
18546.461931] kflat: flatten started
[18546.508386] kflat: flatten_plain_type - zero size memory
[18546.508416] kflat: Done working with 10 recipes in total time 0 [ms], memory used: 1062848, memory avail: 134217728 
[18546.508432] kflat: Flatten done: error=22
[18546.523573] kflat: flatten finished - returning to INTERRUPTED function
```

The `length` field is definitely non-zero (I wrote a simple client to check this), so I'm unsure why this `zero size memory` is happening. Any ideas?

**EDIT:**

When I use `AGGREGATE_FLATTEN_TYPE_ARRAY(u8, value, 32)` it also works fine.

**Comment by bzator** [comment]
Hello @adrianherrera 

This log is generated whenever you're trying to serialize a chunk of memory and you provide the size of 0:
https://github.com/Samsung/kflat/blob/8ab4a57c478aa1c5866f7550f499bfdbaf3d4d73/core/flatten_impl.c#L1684

Did you check all the instances of this struct property for the `length` attribute having non-zero value? Please remember that all instances that are linked together will be serialized iteratively.

Please try the following (change the recipe as follows):
```c
FUNCTION_DEFINE_FLATTEN_STRUCT(property,
    AGGREGATE_FLATTEN_STRING(name);
    if (ATTR(length)!=0) {
        AGGREGATE_FLATTEN_TYPE_ARRAY(u8, value, ATTR(length));
    }
(...)
);
```

**Comment by adrianherrera** [comment]
Yup that check worked! Sorry, I did have a look at some results in my unflatten client to check if there were any zero values and didn't see any. But some must have slipped through.

Thanks very much for your help @bzator!
